#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/nomlify-icon-light.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Nomlify                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Tvá osobní kuchařka pro nejmenší

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nomlify
your_link                                 : https://nomlify.com                     
email_address                             : info@nomlify.com
facebook_username                         : Nomlify                                          
instagram_username                        : nom.li.fy
# twitter_username                          : 
# github_username                           : 
# youtube_username                          :
# mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Zobrazování a vyhledávání receptů
    description                           : ... wow 🤯
    fontawesome_icon_name                 : mobile

  - title                                 : Nahrání receptů „odkudkoli“
    description                           : ... líbí se ti nějaký recept na blogu, Instagramu, v knize? Super! Vyfoť si jej nebo si jej sdílej přímo do aplikace. Máš tak jednoduše k dispozici vše na jednom místě.
    fontawesome_icon_name                 : magic
    
  - title                                 : Alternativní suroviny
    description                           : ... chybí ti něco nebo se ti některá ze surovin nezdá, použij alternativu nebo zkus surovinu odstranit. Recept se ti automaticky upraví 😉.
    fontawesome_icon_name                 : adjust

  - title                                 : Plánování jídel
    description                           : ... pomůžeme ti sestavit jídelníček na týden dopředu tak, ať víš dopředu, co budeš chystat, a máš doma vše potřebné.
    fontawesome_icon_name                 : list

  - title                                 : Pomoc při nákupech
    description                           : ... jo super, máš apku co ti se vším poradí, ale tak nějak ti chybí suroviny. Nikdy více! Teď máš vše poruce a není nic jednoduššího, než si vygenerovat nákupní seznam, případně ho sdílet partnerovi, rodičům nebo si rovnou udělat objednávku například na rohlik.cz 😊
    fontawesome_icon_name                 : share-alt


  # - title                                 : iPhone Device Preview
  #   description                           : Preview your app in the context of an iPhone device. Five different device colors included.
  #   fontawesome_icon_name                 : mobile

  # - title                                 : Video Support
  #   description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #   fontawesome_icon_name                 : play-circle

  # - title                                 : Automatic Icon and Metadata
  #   description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #   fontawesome_icon_name                 : sync

  # - title                                 : Easy to Tweak
  #   description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/nomlify-background.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#6c0942"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#a01368"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
